name: YinwuRaid
version: '${project.version}'
main: org.yinwu.YinwuRaidPlugin
api-version: '1.21'
description: 一个为 Folia 核心设计的倒置信标和特殊袭击插件
author: Qumingjam
website: server.yinwurealm.org
softdepend: [YinwuForge, YinwuEnchant]

# Folia 兼容 - 使用区域线程调度
folia-supported: true

commands:
  yinwuraid:
    description: 灾厄袭击主命令
    usage: /yinwuraid help
    aliases: [yr]
    permission: yinwu.raid.use

permissions:
  yinwu.raid.use:
    description: 使用灾厄袭击命令
    default: true
  yinwu.raid.admin:
    description: 管理灾厄袭击
    default: op
  yinwuraid.beacon.use:
    description: 允许使用倒置信标
    default: true
  yinwuraid.raid.participate:
    description: 参与特殊袭击
    default: true
